apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTkRjd056Y3pOemd3SGhjTk1qVXdOVEV5TVRreE5qRTRXaGNOTXpVd05URXdNVGt4TmpFNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTkRjd056Y3pOemd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUTHlmcE9PbkdyMnVWNk5YaHVHUTJEd2NwYm1FTGE4Ly9QOXZ1dGpMUzUKV1A1c1BMMWtCelJWWExOVHZDTWtMQVp3bUdDL2dsYUhkaWVONHRwaEFrYmJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTVyN2tnMkROY21ycVFLTTJvVjBLCmt0WjFYOG93Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnUCtjcmFUY1Q0NjVQc2YyUjVhc21KZGR1UisrVUFaWFoKbWhOdHBJUzlzNUVDSUFJKy91emhkNzQvVkhoTGNOc2lqZUhWL3NZYUZwVzVUelB6NHBBUXVXT0EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://host.docker.internal:64768
  name: k3d-mycluster
- cluster:
    certificate-authority: C:\Users\krist\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Mon, 30 Jun 2025 22:48:37 CEST
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: cluster_info
    server: https://127.0.0.1:50106
  name: minikube
contexts:
- context:
    cluster: k3d-mycluster
    user: admin@k3d-mycluster
  name: k3d-mycluster
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Mon, 30 Jun 2025 22:48:37 CEST
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: admin@k3d-mycluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJSlA0WHVaTzlBRWt3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelEzTURjM016YzRNQjRYRFRJMU1EVXhNakU1TVRZeE9Gb1hEVEkyTURVeApNakU1TVRZME1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFTVVvSEY4K09uTklTK3gKMHd3QVVQMTdMVXl5NEhzNmhkY0xJWFcwajNoQy9URkd2TmRveUx3TzJEYkh3bytsVGVTZXd5QVJUaUFxYnNveQpObUlvRmtXalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUUloNVQ0VHgvQ2t0SldEbjZia1V3NjRhdlEvakFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQWpjN3lRWGVyRXRGUG5ZTktlbmdpMlJSMHZiUngyY0FZUWlMQXNKZ1lDekFDSVFESzdIc21ESzFTRUpnMQpFQ0loL2N1UTVySWVxMWp4QzkvYytRR1hlaXFQR2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM05EY3dOemN6Tnpnd0hoY05NalV3TlRFeU1Ua3hOakU0V2hjTk16VXdOVEV3TVRreE5qRTQKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM05EY3dOemN6Tnpnd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUlVMbTFyWjBVQVVSN0E4S3dxOXl5czVpSGNqeGlIY1AvVnJOeGhzdGZQCjFUd2ZrM1ErQVVlSXRqU2xESmV0aGlTUjdiWTBlVkNEQ2FpVTRudmEveDRlbzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVDSWVVK0U4ZndwTFNWZzUrbTVGTQpPdUdyMFA0d0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ1lCL0hmVFgvTmdqWDc0VXphU0E3OUtQNUdCRk1odEYyCldYQzFaejRTVHZZQ0lRRGZLYldZQWJuN3YwTTEwTWxvR2gzUlhoUFJTejhtayt4ejVhTktBcmpSeVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1zRFdOUWk3OTUvSGlKTnI3RnFTZFdhU1lNbXdVeWhvUkF5cXBhNDFJbkFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUXhTZ2NYejQ2YzBoTDdIVERBQlEvWHN0VExMZ2V6cUYxd3NoZGJTUGVFTDlNVWE4MTJqSQp2QTdZTnNmQ2o2Vk41SjdESUJGT0lDcHV5akkyWWlnV1JRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
- name: minikube
  user:
    client-certificate: C:\Users\krist\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\krist\.minikube\profiles\minikube\client.key
