version: "3.9"

services:
  backend:
    build:
      context: ./fashionApp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kikis
    depends_on:
      - db

  frontend:
    build:
      context: ./fashion-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kikis
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  pgdata:
  jenkins_home:
